export const AccountLocators = {
  newButton: "button[name='New'], a[title='New'], button:has-text('New')",
  saveButton: 'Save',
  successToast: '',
  detailsTab: "a[title='Details']",
  listViewDropdown: "button[title='Select a List View'], button:has-text('Select a List View')",
  listViewOption: "[role='listbox'] [role='option'], [role='listbox'] li",
  listSearchInput: "input[placeholder='Search this list...'], input[aria-label='Search this list...']",
  tableRows: 'table tbody tr',
  rowLink: 'th a, td a',
  //ageValue: "//records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-number | //records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-text",
  serviceDeliveryAddressValue: "//records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address')]/ancestor::records-record-layout-item//lightning-formatted-address | //records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address')]/ancestor::records-record-layout-item//slot//span",
  personaccount: "//span[text()='Person Account']",
  button: "Next",
  first_name: "First Name",
  last_name: "Last Name",
  email: "Email",
  phone: "Phone",
  dob: "Date of Birth",
  customer_category: "Customer Category",
  Search_Service_address: "Search Service Delivery Address Here",
  copy_address: "Copy to Billing Address",
  Billing_country: "Billing Country",
  Billing_street: "Billing Street",
  Billing_City: "Billing City",
  Billing_state: "Billing State/Province",
  Billing_postalcode: "Billing PostalCode",
  more_Tabs: "button[title='More Tabs'] >> nth=0",
  StoryDescription: "textarea[name='caredescription']",
  Goals: "textarea[name='Name'] >>nth=0",
  currentSituation: "textarea[name='ProblemName']",
  needstobeDone: "textarea[name='ProblemDescription']",
  whom: "textarea[name='By_whom__c']",
  byWhen: "textarea[name='By_when__c']",
  progress:"textarea[name='Progress_and_review__c']",
  task:"textarea[name='Name'] >>nth=-1",
  planprovided:"input[name='planProvided']",
  selectDropdown:"input[placeholder='Select an Option']",
  body: "body",
  launchAddressVerifyLink:
    "xpath=//span[text()='Launch Address / Verify']",
    ageRow:
    "xpath=(//span[contains(@class,'test-id__field-label') and normalize-space()='Age']/ancestor::div[contains(@class,'slds-form-element')][1] | //*[normalize-space()='Age']/ancestor::records-record-layout-item[1])[1]",
  ageValue:
    "xpath=(//div[@class='slds-form-element__control']//ancestor::lightning-formatted-number)",
  verifyAddressInput:
    "input[placeholder='Search Address Here'], input[aria-label='Search Address Here'], input[role='combobox'][aria-autocomplete='list']",
  addressSuggestionItems: "[role='listbox'] [role='option']:visible, ul li:visible",
  searchAddressInput:
    "input[aria-label='Search Address Here'], input[placeholder='Search Address Here'], input[aria-label='Search Service Delivery Address Here'], input[placeholder='Search Service Delivery Address Here']",
  verifyAndSaveButton: "button:has-text('Verify & Save')",
    fallbackAddressInput: "xpath=(//label[contains(normalize-space(),'Address')]/following::input[1])[1]",
    saveToast: "text=Address verified and saved, text=Saved, [role='alert']",
    addressInformationText: "button:has-text('Address Information')",
      addressValue: "[data-target-selection-name='sfdc:RecordField.Lead.Address']",
      SelectClientFormCategory: "button[aria-label='Select Category']",
      listviewdropdownaccount:"button[title='Select a List View: Accounts']"


} as const;
