export const AccountLocators = {
  newButton: "button[name='New']",
  saveButton: 'Save',
  successToast: '',
  detailsTab: "a[title='Details']",
  ageValue: "//records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-number | //records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-text",
  serviceDeliveryAddressValue: "//records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address')]/ancestor::records-record-layout-item//lightning-formatted-address | //records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address')]/ancestor::records-record-layout-item//slot//span",
  personaccount: "//span[text()='Person Account']",
  button: "Next",
  first_name: "First Name",
  last_name: "Last Name",
  email: "Email",
  phone: "Phone",
  dob: "Date of Birth",
  customer_category: "Customer Category",
  Search_Service_address: "Search Service Delivery Address Here",
  copy_address: "Copy to Billing Address",
  Billing_country: "Billing Country",
  Billing_street: "Billing Street",
  Billing_City: "Billing City",
  Billing_state: "Billing State/Province",
  Billing_postalcode: "Billing PostalCode",

} as const;
