export const AccountLocators = {
  newButton: "button[name='New'], a[title='New'], button:has-text('New')",
  saveButton: 'Save',
  successToast: '',
  detailsTab: "a[title='Details']",
  listViewDropdown: "button[title='Select a List View'], button:has-text('Select a List View')",
  listViewOption: "[role='listbox'] [role='option'], [role='listbox'] li",
  listSearchInput: "input[placeholder='Search this list...'], input[aria-label='Search this list...']",
  tableRows: 'table tbody tr',
  rowLink: 'th a, td a',
  ageValue: "//records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-number | //records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-text",
  serviceDeliveryAddressValue: "//records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address')]/ancestor::records-record-layout-item//lightning-formatted-address | //records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address')]/ancestor::records-record-layout-item//slot//span",
  personaccount: "//span[text()='Person Account']",
  button: "Next",
  first_name: "First Name",
  last_name: "Last Name",
  email: "Email",
  phone: "Phone",
  dob: "Date of Birth",
  customer_category: "Customer Category",
  Search_Service_address: "Search Service Delivery Address Here",
  copy_address: "Copy to Billing Address",
  Billing_country: "Billing Country",
  Billing_street: "Billing Street",
  Billing_City: "Billing City",
  Billing_state: "Billing State/Province",
  Billing_postalcode: "Billing PostalCode",
  more_Tabs: "button[title='More Tabs'] >> nth=0",
  StoryDescription: "textarea[name='caredescription']",
  Goals: "textarea[name='Name'] >>nth=0",
  currentSituation: "textarea[name='ProblemName']",
  needstobeDone: "textarea[name='ProblemDescription']",
  whom: "textarea[name='By_whom__c']",
  byWhen: "textarea[name='By_when__c']",
  progress:"textarea[name='Progress_and_review__c']",
  task:"textarea[name='Name'] >>nth=-1",
  planprovided:"input[name='planProvided']",
  selectDropdown:"input[placeholder='Select an Option']",
} as const;
