export const AppointmentLocators = {
  newButton: "button:has-text('New'), lightning-button:has-text('New')",
  listViewDropdown: "button[title*='Select a List View'], button[aria-label*='List View'], .triggerLink",
  listViewOption: "[role='option'], [role='menuitemradio'], .slds-listbox__option",
  listSearchInput: "input[placeholder*='Search this list'], input[placeholder*='Search']",
  tableRows: "table tbody tr",
  rowLink: "th a, td a",
  pageHeader: "h1, .slds-page-header__title",
  informationSection: "xpath=//*[normalize-space()='Information']",
  typeValue: "xpath=//*[normalize-space()='Type']/following::lightning-formatted-text[1]",
  statusValue: "xpath=//*[normalize-space()='Status']/following::lightning-formatted-text[1]",
  serviceValue: "xpath=//*[normalize-space()='Service']/following::lightning-formatted-text[1]",
  addFilesButton: "text=Add Files",
  deliveryActivitiesHeader: "xpath=//span[contains(normalize-space(),'Delivery Activities')]",
  deliveryActivityRows: "xpath=//span[contains(normalize-space(),'Delivery Activities')]/ancestor::article[1]//table/tbody/tr",
  appLauncherButton:"button[title='App Launcher']",
  entersearchLaunch:"input[placeholder='Search apps and items...']",
  deliveryActivityInformationSection: "xpath=//*[normalize-space()='Information']",
  deliveryActivityStatusValue: "xpath=//*[normalize-space()='Status']/following::lightning-formatted-text[1]",
  appointmentServiceInfoSection: "xpath=//*[normalize-space()='Appointment Service Information']",
  appointmentServiceValue: "xpath=//*[normalize-space()='Appointment Service']/following::*[self::a or self::lightning-formatted-text][1]",
  billingFundingSection: "xpath=//*[normalize-space()='Billing and Funding Information']",
  invoiceLineItemValue: "xpath=//*[normalize-space()='Invoice Line Item']/following::*[self::a or self::lightning-formatted-text][1]",
  agreementItemValue: "xpath=//*[normalize-space()='Agreement Item']/following::*[self::a or self::lightning-formatted-text][1]",
} as const;
