export const LeadLocators = {
  newButton: "button[name='New']",
  convertButton: "button:has-text('Convert')",
  convertFirstNameInput: "input[name='firstName']",
  convertLastNameInput: "input[name='lastName']",
  convertOpportunityNameInput: "input[name='opptyName']",
  convertConfirmButton: "button:has-text('Convert')",
  conversionSuccessMessage: "text=Your lead has been converted",
  goToLeadsButton: "button:has-text('Go to Leads')",
  leadsListSearchInput: "input[placeholder='Search this list...']",
  detailsTab: "a[title='Details']",
  launchAddressVerifyLink: "a:has-text('Launch Address / Verify')",
  verifyAddressInput: "input[placeholder='Search Address Here'], input[aria-label='Search Address Here']",
  addressSuggestionItems: "ul li, [role='listbox'] [role='option']",
  verifyAndSaveButton: "button:has-text('Verify & Save')",
  dobValue: "//records-record-layout-item//*[normalize-space(text())='Date of Birth']/ancestor::records-record-layout-item//lightning-formatted-text",
  ageValue: "//records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-number | //records-record-layout-item//*[normalize-space(text())='Age']/ancestor::records-record-layout-item//lightning-formatted-text",
  addressValue: "//records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address') or contains(normalize-space(text()),'Address')]/ancestor::records-record-layout-item//lightning-formatted-address | //records-record-layout-item//*[contains(normalize-space(text()),'Service Delivery Address') or contains(normalize-space(text()),'Address')]/ancestor::records-record-layout-item//slot//span",
  lead_source: "Lead Source",
  first_name: "First Name",
  last_name: "Last Name",
  email: "Email",
  phone: "Phone",
  service_requested: "Service Request",
  Additional_information: "Additional Information",
  dob : "Date of Birth",
  search_address: "Search Address Here",
  lead_Score: "Lead Score",
  save_button: "Save",
} as const;
