export const LeadLocators = {
  leadsHeader: "xpath=(//*[normalize-space()='Leads'])[1]",
  createLeadTitle: "text=Create Lead",
  visibleDropdownOptions: "[role='option']:visible, ul li:visible",
  listboxOptionsWithTitle: "[role='listbox'] [role='option'], [role='listbox'] li, [role='listbox'] span[title]",
  leadScoreHotOption: "[role='option']:visible, ul li:visible >> text=Hot",
  fallbackAddressInput: "xpath=(//label[contains(normalize-space(),'Address')]/following::input[1])[1]",
  leadsListSearchInput: "input[placeholder='Search this list...']",
  leadTableRows: "table tbody tr",
  leadRowLink: "th a, a",
  convertButtonPrimary: ".slds-page-header button[name='Convert']:visible",
  convertButtonFallback: "button[name='Convert']:visible",
  modalContainer: ".modal-container, .forceModal, .slds-modal",
  conversionDialog: "section[role='dialog'], .slds-modal",
  ageInput: "input[aria-label='Age']",
  body: "body",
  addressInformationText: "button:has-text('Address Information')",
  saveToast: "text=Address verified and saved, text=Saved, [role='alert']",
  dobInputVisible: "input[aria-label='Date Of Birth']:visible, input[aria-label='Date of Birth']:visible",
  detailsTab: "a[title='Details'], [role='tab']:has-text('Details'), a:has-text('Details')",
  launchAddressVerifyLink:
    "xpath=//span[text()='Launch Address / Verify']",
  verifyAddressInput:
    "input[placeholder='Search Address Here'], input[aria-label='Search Address Here'], input[role='combobox'][aria-autocomplete='list']",
  addressSuggestionItems: "[role='listbox'] [role='option']:visible, ul li:visible",
  searchAddressInput:
    "input[aria-label='Search Address Here'], input[placeholder='Search Address Here'], input[aria-label='Search Service Delivery Address Here'], input[placeholder='Search Service Delivery Address Here']",
  verifyAndSaveButton: "button:has-text('Verify & Save')",
  dobRow:
    "xpath=(//span[contains(@class,'test-id__field-label') and (normalize-space()='Date of Birth' or normalize-space()='Date Of Birth')]/ancestor::div[contains(@class,'slds-form-element')][1] | //*[normalize-space()='Date of Birth' or normalize-space()='Date Of Birth']/ancestor::records-record-layout-item[1])[1]",
  dobValue:
    "xpath=(//*[normalize-space()='Date of Birth' or normalize-space()='Date Of Birth']/following::*[self::lightning-formatted-text or self::span][1] | //records-record-layout-item//*[normalize-space()='Date of Birth' or normalize-space()='Date Of Birth']/ancestor::records-record-layout-item//*[self::lightning-formatted-text or self::span][contains(normalize-space(),'/' )][1])",
  ageRow:
    "xpath=(//span[contains(@class,'test-id__field-label') and normalize-space()='Age']/ancestor::div[contains(@class,'slds-form-element')][1] | //*[normalize-space()='Age']/ancestor::records-record-layout-item[1])[1]",
  ageValue:
    "xpath=(//div[@class='slds-form-element__control']//ancestor::lightning-formatted-number)",
  addressValue: "[data-target-selection-name='sfdc:RecordField.Lead.Address']",
  Agevalue: "xpath=(//div[@class='slds-form-element__control']//ancestor::lightning-formatted-number)",
  AgeText: "xpath=(//span[text()='Age'])",
  lead_source: "Lead Source",
  primary_language: "Primary Language",
  secondary_language: "Secondary Language",
  interpreter_required: "Interpreter Required",
  preferred_contact_method: "Preferred Contact Method",
  relationship: "Relationship",
  marketing_communication_opt_in: "input[aria-label='Marketing Communication']",
  marketing_communication_preference: "input[aria-label='Marketing Communication Preference']",
  first_name: "First Name",
  last_name: "Last Name",
  email: "Email",
  phone: "Phone",
  service_requested: "Service Request",
  Additional_information: "Additional Information",
  dob : "Date of Birth",
  search_address: "Search Address Here",
  lead_Score: "Lead Score",
  save_button: "Save",
} as const;
