export const OpportunityLocators = {
  newButton: "button[name='New']",
  accountNameInput: "input[aria-label='Account Name'], input[placeholder='Search Accounts...']",
  accountNameOptions: "[role='listbox'] [role='option'], ul li",
  firstOpportunityLink: "//table//tbody//tr[1]//th//a | //table//tbody//tr[1]//a[contains(@title,'HC -')]",
  listSearchInput: "input[placeholder='Search this list...']",
  listViewDropdown: "[role='button'][aria-haspopup='listbox'], button[title*='List View'], button[aria-label*='List View']",
  listViewOption: "[role='listbox'] [role='option'], [role='listbox'] li",
  tableRows: "table tbody tr",
  rowLink: "th a, a",
  detailsTab: "a[title='Details']",
  fundingDetailsSection: "button:has-text('Funding Details'):visible, span[title='Funding Details']:visible",
  fundingSourceEditButton: "button[title='Edit Funding Source']",
  fundingSourceLabel: "xpath=//*[normalize-space(text())='Funding Source']",
  fundingTypeLabel: "xpath=//*[normalize-space(text())='Funding Type']",
  fundingSourceValue: "xpath=(//*[normalize-space(text())='Funding Source']/following::*[contains(@class,'slds-form-element__static') or self::lightning-formatted-text or self::span][1])[1]",
  fundingTypeValue: "xpath=(//*[normalize-space(text())='Funding Type']/following::*[contains(@class,'slds-form-element__static') or self::lightning-formatted-text or self::span][1])[1]",
  fundingValue: "xpath=(//*[normalize-space(text())='Funding']/following::*[self::a or contains(@class,'slds-form-element__static') or self::lightning-formatted-text or self::span][1])[1]",
  assessmentVisitPreferenceDropdown: "xpath=(//label[contains(normalize-space(),'Assessment visit preference')]/following::button[@role='combobox'][1])[1]",
  virtualOption: "xpath=(//*[@role='option' and normalize-space()='Virtual'])[1]",
  opportunitySaveButton: "xpath=(//button[normalize-space()='Save'])[1]",
  fundingSourceDropdown: "xpath=(//*[@aria-label='Funding Source' and @role='combobox'] | //label[normalize-space()='Funding Source']/following::button[@role='combobox'][1])[1]",
  fundingTypeDropdown: "xpath=(//*[@aria-label='Funding Type' and @role='combobox'] | //label[normalize-space()='Funding Type']/following::button[@role='combobox'][1])[1]",
  supportAtHomeOption: "xpath=//*[@role='option' and normalize-space()='Support at Home']",
  fundingSearchInput: "xpath=(//input[contains(@placeholder,'Search Funding') or @aria-label='Funding'])[1]",
  newFundingOption: "xpath=(//*[@role='option' and normalize-space()='New Funding'] | //span[normalize-space()='New Funding'])[1]",
  participantInput: "xpath=(//input[@placeholder='Search Contacts...' or @aria-label='Participant'])[1]",
  participantFirstResult: "xpath=((//input[@placeholder='Search Contacts...' or @aria-label='Participant'])[1]/following::ul[contains(@class,'slds-listbox')][1]//li[1])[1]",
  newFundingSourceDropdown: "xpath=(//label[normalize-space()='Funding Source']/following::button[@role='combobox'][1])[1]",
  newFundingTypeDropdown: "xpath=(//label[normalize-space()='Funding Type']/following::button[@role='combobox'][1])[1]",
  newFundingSaveButton: "xpath=(//button[normalize-space()='Save'])[last()]",
} as const;
