export const OpportunityLocators = {
  newButton: "button[name='New']",
  accountNameInput: "input[aria-label='Account Name'], input[placeholder='Search Accounts...']",
  accountNameOptions: "[role='listbox'] [role='option'], ul li",
  firstOpportunityLink: "//table//tbody//tr[1]//th//a | //table//tbody//tr[1]//a[contains(@title,'HC -')]",
  listSearchInput: "input[placeholder='Search this list...']",
  listViewDropdown: "[role='button'][aria-haspopup='listbox'], button[title*='List View'], button[aria-label*='List View']",
  listViewOption: "[role='listbox'] [role='option'], [role='listbox'] li",
  tableRows: "table tbody tr",
  rowLink: "th a, a",
  detailsTab: "a[title='Details']",
  fundingDetailsSection: "button:has-text('Funding Details'):visible, span[title='Funding Details']:visible",
  fundingSourceEditButton: "button[title='Edit Funding Source']",
  fundingSourceLabel: "xpath=//*[normalize-space(text())='Funding Source']",
  fundingTypeLabel: "xpath=//*[normalize-space(text())='Funding Type']",
  fundingSourceValue: "xpath=(//*[normalize-space(text())='Funding Source']/following::*[contains(@class,'slds-form-element__static') or self::lightning-formatted-text or self::span][1])[1]",
  fundingTypeValue: "xpath=(//*[normalize-space(text())='Funding Type']/following::*[contains(@class,'slds-form-element__static') or self::lightning-formatted-text or self::span][1])[1]",
  fundingValue: "xpath=(//*[normalize-space(text())='Funding']/following::*[self::a or contains(@class,'slds-form-element__static') or self::lightning-formatted-text or self::span][1])[1]",
  assessmentVisitPreferenceDropdown: "xpath=(//label[contains(normalize-space(),'Assessment visit preference')]/following::button[@role='combobox'][1])[1]",
  virtualOption: "xpath=(//*[@role='option' and normalize-space()='Virtual'])[1]",
  opportunitySaveButton: "xpath=(//button[normalize-space()='Save'])[1]",
  fundingSourceDropdown: "xpath=(//*[@aria-label='Funding Source' and @role='combobox'] | //label[normalize-space()='Funding Source']/following::button[@role='combobox'][1])[1]",
  fundingTypeDropdown: "xpath=(//*[@aria-label='Funding Type' and @role='combobox'] | //label[normalize-space()='Funding Type']/following::button[@role='combobox'][1])[1]",
  supportAtHomeOption: "xpath=//*[@role='option' and normalize-space()='Support at Home']",
  fundingSearchInput: "xpath=(//input[contains(@placeholder,'Search Funding') or @aria-label='Funding'])[1]",
  newFundingOption: "xpath=(//*[@role='option' and normalize-space()='New Funding'] | //span[normalize-space()='New Funding'])[1]",
  participantInput: "xpath=(//input[@placeholder='Search Contacts...' or @aria-label='Participant'])[1]",
  participantFirstResult: "xpath=((//input[@placeholder='Search Contacts...' or @aria-label='Participant'])[1]/following::ul[contains(@class,'slds-listbox')][1]//li[1])[1]",
  newFundingSourceDropdown: "xpath=(//label[normalize-space()='Funding Source']/following::button[@role='combobox'][1])[1]",
  newFundingTypeDropdown: "xpath=(//label[normalize-space()='Funding Type']/following::button[@role='combobox'][1])[1]",
  newFundingSaveButton: "xpath=(//button[normalize-space()='Save'])[last()]",
  listboxOptions: "[role='listbox'] [role='option'], [role='listbox'] li, [role='listbox'] span[title]",
  detailsTabByTitle: "a[title='Details']",
  fundingSourceVisibleLabel: "span.test-id__field-label:has-text('Funding Source'):visible",
  fundingSourceLabels: "span.test-id__field-label",
  fundingSourceEditInField: "xpath=ancestor::record_flexipage-record-field[1]//button[contains(@title,'Edit Funding Source')]",
  fundingTypeComboboxButton: "button[role='combobox'][aria-label*='Funding Type']",
  fundingTypeComboboxInput: "input[role='combobox'][aria-label*='Funding Type']",
  participantSearchInput: "input[placeholder='Search Contacts...']",
  searchIconInCombobox:
    "xpath=ancestor::div[contains(@class,'slds-combobox')]//button[contains(@title,'Search') or contains(@aria-label,'Search')]",
  advancedSearchParticipantInput: "input[aria-label='Participant']",
  advancedSearchFirstRowRadio: "table tbody tr label.slds-radio__label",
  advancedSearchSelectButton:
    "lightning-modal-footer button.slds-button_brand:has-text('Select'), button.slds-button_brand:has-text('Select')",
  newFundingSourceDropdownInModal: "xpath=(//button[@aria-label='Funding Source'])[2]",
  newFundingTypeDropdownInModal: "xpath=(//button[@aria-label='Funding Type'])[2]",
  newFundingSaveButtonInModal: "xpath=(//button[text()='Save'])[2]",
  assessmentVisitPreferenceDropdownByAria: "button[aria-label='Assessment visit preference?']",
  inPersonOptionText: "In-Person",
  serviceAgreementStatusDropdown: "button[aria-label='Service Agreement Status']",
  serviceAgreementSignedOptionText: "Signed",
  referrerTypeDropdownByAria: "xpath=(//button[@aria-label='Referrer Type'])",
  referrerTypeFamilyViolenceOptionText: "Family violence programs",
  saveButtonByText: 'xpath=(//button[text()="Save"])',
  generateQuoteButton: 'xpath=(//button[text()="Generate Quote"])',
  quoteErrorText: 'xpath=(//p[text()="Quote cannot be generated as no products available for this opportunity."])',
  closeButtonByText: 'xpath=(//button[text()="Close"])',
  relatedTabText: 'Related',
  choosePriceBookText: 'Choose Price Book',
  priceBookInput: 'input[aria-label="Price Book"]',
} as const;
